use_frameworks!

platform :ios, '8.0'

target 'LHTools_Example' do
  pod 'LHTools', :path => '../'

  target 'LHTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
